services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: bankcore-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bankcore}
      POSTGRES_USER: ${POSTGRES_USER:-bankcore}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - bankcore_postgres_data:/var/lib/postgresql/data

volumes:
  bankcore_postgres_data:
