spring.application.name=REDACTED_DATABASE_PASSWORD

# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/REDACTED_DATABASE_PASSWORD
spring.datasource.username=REDACTED_DATABASE_PASSWORD
spring.datasource.password=REDACTED_DATABASE_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ==========================================
# SERVER
# ==========================================

server.port=8080

# ==========================================
# JWT
# ==========================================

jwt.secret=REDACTED_JWT_SECRET
jwt.expiration=86400000

# ==========================================
# LOGGING
# ==========================================

logging.level.com.REDACTED_DATABASE_PASSWORD=INFO

# ===============================
# Spring AI - OpenAI
# ===============================

spring.ai.google.genai.api-key=REDACTED_GEMINI_API_KEY
spring.ai.google.genai.chat.model=gemini-3.5-flash-lite

# ============================================================
# GEMINI EMBEDDINGS
# ============================================================

spring.ai.google.genai.embedding.api-key=REDACTED_GEMINI_API_KEY
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.dimensions=768


# ============================================================
# PGVECTOR
# ============================================================

spring.ai.vectorstore.pgvector.initialize-schema=true

spring.ai.vectorstore.pgvector.index-type=HNSW

spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

spring.ai.vectorstore.pgvector.dimensions=768
